run:
  skip-dirs:
    - swagger
    - graph/handler
    - graph/playground
    - hack
linters:
  enable:
    - revive
    - govet
linters-settings:
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    enableAllRules: true
    rules:
      - name: add-constant
        disabled: true
      # - name: argument-limit
      #   arguments: [5]
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: confusing-naming
      - name: confusing-results
      - name: cognitive-complexity
        # arguments: [7]
        disabled: true
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: cyclomatic
        # arguments: [3]
        disabled: true
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: file-header
        disabled: true
      - name: flag-parameter
      - name: function-result-limit
        arguments: [4]
      - name: function-length
        disabled: true
        # arguments: [10,0]
      - name: get-return
      - name: identical-branches
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: imports-blacklist
      - name: import-shadowing
      - name: line-length-limit
        disabled: true
        arguments: [150]
      - name: max-public-structs
        disabled: true
      - name: modifies-parameter
      - name: modifies-value-receiver
      # - name: nested-structs 当前版本不支持
      #   disabled: true
      - name: package-comments
      - name: range
      - name: range-val-in-closure
      - name: range-val-address
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: struct-tag
      - name: string-format
      - name: superfluous-else
      - name: time-naming
      - name: var-naming
        arguments:
          - [ID]  # whitelist，不要求严格大小写，可以写成 ID，也可以写成 Id
          - [VM]  # blacklist，必须严格按此大小写，只能写成 VM，不能写成 Vm
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unhandled-error
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: waitgroup-by-value
  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 10