package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"fmt"

	"github.com/speedoops/go-gqlrest-demo/graph/model"
	generated1 "github.com/speedoops/go-gqlrest-demo/graph/zgenerated"
)

// OldFoo is the resolver for the oldFoo field.
func (r *overlappingFieldsResolver) OldFoo(ctx context.Context, obj *model.OverlappingFields) (int, error) {
	panic(fmt.Errorf("not implemented"))
}

// Overlapping is the resolver for the overlapping field.
func (r *queryResolver) Overlapping(ctx context.Context) (*model.OverlappingFields, error) {
	panic(fmt.Errorf("not implemented"))
}

// OverlappingFields returns generated1.OverlappingFieldsResolver implementation.
func (r *Resolver) OverlappingFields() generated1.OverlappingFieldsResolver {
	return &overlappingFieldsResolver{r}
}

type overlappingFieldsResolver struct{ *Resolver }
