package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"github.com/speedoops/go-gqlrest-demo/graph/zgenerated"
)

// Mutation returns zgenerated.MutationResolver implementation.
func (r *Resolver) Mutation() zgenerated.MutationResolver { return &mutationResolver{r} }

// Query returns zgenerated.QueryResolver implementation.
func (r *Resolver) Query() zgenerated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
