// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userID"`
	Done   *bool  `json:"done"`
}

type UpdateTodoInput struct {
	ID     string  `json:"id"`
	Text   *string `json:"text"`
	UserID *string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

type EnumType string

const (
	EnumTypeA EnumType = "A"
	EnumTypeB EnumType = "B"
)

var AllEnumType = []EnumType{
	EnumTypeA,
	EnumTypeB,
}

func (e EnumType) IsValid() bool {
	switch e {
	case EnumTypeA, EnumTypeB:
		return true
	}
	return false
}

func (e EnumType) String() string {
	return string(e)
}

func (e *EnumType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EnumType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EnumType", str)
	}
	return nil
}

func (e EnumType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
